### ISSUE TITLE
Sqlalchemy connection is missed when database service restarts or the connection is renewed

### ISSUE THREAD

**Issue by piraz** [candango/firenado#127]
Just notice an application that after some time starts to throws a 500 error instead of rendering the page correctly.

The root cause of this issue is the mysql connection is tunnelled and some times the daemon renews the connection. Pymysql connection is gone and a error similar to this one can be seem at the log: 
```
WARNING - firenado.data[data:215] - 2016-07-30 22:49:44,773 - (pymysql.err.InternalError) Packet sequence number wrong - got 0 expected 1 [SQL: u'select now() as testtime;']
ERROR - sqlalchemy.pool.QueuePool[pool:643] - 2016-07-30 22:49:44,773 - Exception during reset or similar
Traceback (most recent call last):
  File "../venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "../venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 774, in _reset
    self._reset_agent.rollback()
  File "../venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1563, in rollback
    self._do_rollback()
  File "../venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1601, in _do_rollback
    self.connection._rollback_impl()
  File "../venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 670, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "../venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "../venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
msm
  File "../venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 668, in _rollback_impl
session
    self.engine.dialect.do_rollback(self.connection)
  File "../venv/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2526, in do_rollback
    dbapi_connection.rollback()
  File "../venv/lib/python2.7/site-packages/pymysql/connections.py", line 771, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "../venv/lib/python2.7/site-packages/pymysql/connections.py", line 1054, in _execute_command
    self._write_bytes(packet)
  File "../venv/lib/python2.7/site-packages/pymysql/connections.py", line 1006, in _write_bytes
    raise err.OperationalError(2006, "MySQL server has gone away (%r)" % (e,))
OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (error(32, 'Broken pipe'))")
INFO - tornado.access[web:1946] - 2016-07-30 22:49:44,789 - 304 GET / (127.0.0.1) 18.22ms
```

This is not the original error but one I provoked trying to reproduce the issue.

The steps to reproduce the issue are:

- Create an application with a mysql data source configured
- Create a handler with some data coming from this mysql data source and render it on a template(or just print it on the request)
- Start the application
- Access the url of this handler and observe the data printed corrected on the response
- Restart the mysql server
- Refresh the page and observe the error on the console log

**Comment by piraz** [comment]
Here are some insight about the issue:

- http://stackoverflow.com/questions/31121948/flask-sqlalchemy-cant-reconnect-until-invalid-transaction-is-rolled-back
- http://stackoverflow.com/questions/23301968/invalid-transaction-persisting-across-requests
- http://stackoverflow.com/questions/8645250/how-to-close-sqlalchemy-connection-in-mysql

**Comment by piraz** [comment]
This is happening on pgsql too. Let's fix it here.
