### ISSUE TITLE
Cannot install on pip 10.

### ISSUE THREAD

**Issue by piraz** [candango/firenado#197]
Error on the setup.py execution, no module named pip.req:

```
python setup.py install
.
.
.
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y4mf_vgf/firenado/setup.py", line 18, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
```
See: https://stackoverflow.com/questions/25192794/no-module-named-pip-req

**Comment by piraz** [comment]
This is the change on pip that caused the issue: https://github.com/pypa/pip/pull/4700
